const ShopItemsData = [
  {
    id: "product1",
    name: "Adapt Animal Seamless Leggings",
    price: 45,
    img: require("../../images/Products/Womens/ADAPT ANIMAL/ADAPT ANIMAL SEAMLESS LEGGINGS1.webp"),
    img2: require("../../images/Products/Womens/ADAPT ANIMAL/ADAPT ANIMAL SEAMLESS LEGGINGS2.webp"),
    img3: require("../../images/Products/Womens/ADAPT ANIMAL/ADAPT ANIMAL SEAMLESS LEGGINGS3.webp"),
    img4: require("../../images/Products/Womens/ADAPT ANIMAL/ADAPT ANIMAL SEAMLESS LEGGINGS4.webp"),
    gender: "f",
  },
  {
    id: "product2",
    name: "Apollo Joggers",
    price: 100,
    img: require("../../images/Products/Men's/APOLLO JOGGERS/APOLLO JOGGERS1.webp"),
    img2: require("../../images/Products/Men's/APOLLO JOGGERS/APOLLO JOGGERS2.webp"),
    img3: require("../../images/Products/Men's/APOLLO JOGGERS/APOLLO JOGGERS3.webp"),
    img4: require("../../images/Products/Men's/APOLLO JOGGERS/APOLLO JOGGERS4.webp"),
    gender: "m",
  },
  {
    id: "product3",
    name: "Bold Stringer",
    price: 25,
    img: require("../../images/Products/Men's/BOLD STRINGER/BOLD STRINGER1.webp"),
    img2: require("../../images/Products/Men's/BOLD STRINGER/BOLD STRINGER2.webp"),
    img3: require("../../images/Products/Men's/BOLD STRINGER/BOLD STRINGER3.webp"),
    img4: require("../../images/Products/Men's/BOLD STRINGER/BOLD STRINGER4.webp"),
    gender: "m",
  },
  {
    id: "product4",
    name: "Training Oversized Jumper",
    price: 300,
    img: require("../../images/Products/Womens/TRAINING OVERSIZED JUMPER/TRAINING OVERSIZED SWEATSHIRT1.webp"),
    img2: require("../../images/Products/Womens/TRAINING OVERSIZED JUMPER/TRAINING OVERSIZED SWEATSHIRT2.webp"),
    img3: require("../../images/Products/Womens/TRAINING OVERSIZED JUMPER/TRAINING OVERSIZED SWEATSHIRT3.webp"),
    img4: require("../../images/Products/Womens/TRAINING OVERSIZED JUMPER/TRAINING OVERSIZED SWEATSHIRT4.webp"),
    gender: "f",
  },
  {
    id: "product5",
    name: "Arrival Woven Joggers",
    price: 16,
    img: require("../../images/Products/Men's/ARRIVAL WOVEN/ARRIVAL WOVEN JOGGERS1.webp"),
    img2: require("../../images/Products/Men's/ARRIVAL WOVEN/ARRIVAL WOVEN JOGGERS2.webp"),
    img3: require("../../images/Products/Men's/ARRIVAL WOVEN/ARRIVAL WOVEN JOGGERS3.webp"),
    gender: "m",
  },
  {
    id: "product6",
    name: "Sport Seamless 1:4 Zip",
    price: 65,
    img: require("../../images/Products/Men's/SPORT SEAMLESS 1:4 ZIP/SPORT SEAMLESS 1:4 ZIP.webp"),
    img2: require("../../images/Products/Men's/SPORT SEAMLESS 1:4 ZIP/SPORT SEAMLESS 1:4 ZIP2.webp"),
    img3: require("../../images/Products/Men's/SPORT SEAMLESS 1:4 ZIP/SPORT SEAMLESS 1:4 ZIP3.webp"),
    img4: require("../../images/Products/Men's/SPORT SEAMLESS 1:4 ZIP/SPORT SEAMLESS 1:4 ZIP4.webp"),
    gender: "m",
  },
  {
    id: "product7",
    name: "Training Cami Tank",
    price: 37,
    img: require("../../images/Products/Womens/TRAINING CAMI TANK/TRAINING CAMI TANK1.webp"),
    img2: require("../../images/Products/Womens/TRAINING CAMI TANK/TRAINING CAMI TANK2.webp"),
    img3: require("../../images/Products/Womens/TRAINING CAMI TANK/TRAINING CAMI TANK3.jpg"),
    gender: "f",
  },
  {
    id: "product8",
    name: "Vital Seamless Leggings",
    price: 88,
    img: require("../../images/Products/Womens/VITAL SEAMLESS LEGGINGS/VITAL SEAMLESS 2.0 LEGGINGS1.webp"),
    img2: require("../../images/Products/Womens/VITAL SEAMLESS LEGGINGS/VITAL SEAMLESS 2.0 LEGGINGS2.webp"),
    img3: require("../../images/Products/Womens/VITAL SEAMLESS LEGGINGS/VITAL SEAMLESS 2.0 LEGGINGS3.webp"),
    img4: require("../../images/Products/Womens/VITAL SEAMLESS LEGGINGS/VITAL SEAMLESS 2.0 LEGGINGS4.webp"),
    gender: "f",
  },
  {
    id: "product9",
    name: "Lifting Wraps",
    price: 12,
    img: require("../../images/Products/Other/WRAP LIFTING GLOVES/WRAP LIFTING GLOVES1.webp"),
    img2: require("../../images/Products/Other/WRAP LIFTING GLOVES/WRAP LIFTING GLOVES2.webp"),
    img3: require("../../images/Products/Other/WRAP LIFTING GLOVES/WRAP LIFTING GLOVES3.webp"),
    img4: require("../../images/Products/Other/WRAP LIFTING GLOVES/WRAP LIFTING GLOVES4.webp"),
    gender: "n",
  },
  {
    id: "product10",
    name: "Garmin Forerunner",
    price: 350,
    img: require("../../images/Products/Other/Garmin/garmin.avif"),
    gender: "n",
  },
  {
    id: "product11",
    name: "Glute Band",
    price: 25,
    img: require("../../images/Products/Other/GLUTE BAND/MEDIUM GLUTE BAND1.webp"),
    img2: require("../../images/Products/Other/GLUTE BAND/MEDIUM GLUTE BAND2.webp"),
    img3: require("../../images/Products/Other/GLUTE BAND/MEDIUM GLUTE BAND3.webp"),
    img4: require("../../images/Products/Other/GLUTE BAND/MEDIUM GLUTE BAND4.webp"),
    gender: "n",
  },
  {
    id: "product12",
    name: "Knee Sleeve",
    price: 19,
    img: require("../../images/Products/Other/KNEE SLEEVE/KNEE SLEEVE 5MM1.webp"),
    img2: require("../../images/Products/Other/KNEE SLEEVE/KNEE SLEEVE 5MM2.webp"),
    img3: require("../../images/Products/Other/KNEE SLEEVE/KNEE SLEEVE 5MM3.webp"),
    img4: require("../../images/Products/Other/KNEE SLEEVE/KNEE SLEEVE 5MM4.webp"),
    gender: "n",
  },
  {
    id: "product13",
    name: "Water Bottle",
    price: 1000,
    img: require("../../images/Products/Other/WATER BOTTLE/1.3L WATER BOTTLE1.webp"),
    img2: require("../../images/Products/Other/WATER BOTTLE/1.3L WATER BOTTLE2.webp"),
    img3: require("../../images/Products/Other/WATER BOTTLE/1.3L WATER BOTTLE3.webp"),
    gender: "n",
  },
];

export default ShopItemsData;
